apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ntko1jsxi-nodejs
  janus-idp.io/tekton: ntko1jsxi-nodejs
  backstage.io/kubernetes-id: ntko1jsxi-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ntko1jsxi-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
